{{- if or (gt .Values.activityrelay.workers.replicaCount 1.0) (.Values.activityrelay.workers.autoscaling.enabled) }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "activityrelay.fullname" . }}-worker
  labels:
    {{- include "activityrelay.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "activityrelay.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
{{- end }}
