apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi.fullname" . }}-tcp
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "unifi.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if (eq .Values.service.type "LoadBalancer") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  ports:
  - name: unifi-network-application-http
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: unifi-network-application-https
    port: 8443
    protocol: TCP
    targetPort: 8443
  - name: unifi-portal-http
    port: 8880
    protocol: TCP
    targetPort: 8880
  - name: unifi-portal-https
    port: 8843
    protocol: TCP
    targetPort: 8843
  - name: throughput
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: metrics
    port: 9130
    protocol: TCP
    targetPort: metrics
  selector:
    {{- include "unifi.selectorLabels" . | nindent 4 }}
