---
{{- if eq .Values.kind "deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflared.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloudflared.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
{{- if .Values.strategy }}
  strategy:
{{ toYaml .Values.strategy | indent 4 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "cloudflared.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "cloudflared.labels" . | nindent 8 }}
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/tunnel-secret.yaml") . | sha256sum }}
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          args:
            - tunnel
            - --no-autoupdate
            - --config
            - /etc/cloudflared/config.yaml
            - run
          ports:
            - name: http
              containerPort: 2000
          livenessProbe:
            httpGet:
              path: /ready
              port: http
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10000
          resources:
{{ toYaml .Values.resources | indent 12 }}
          volumeMounts:
            - name: tunnel-secret-volume
              subPath: {{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json
              mountPath: /etc/cloudflared/{{ required "A valid .Values.tunnelID entry required!" .Values.tunnelID }}.json
            - name: cloudflared-config-volume
              subPath: config.yaml
              mountPath: /etc/cloudflared/config.yaml
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      volumes:
        - name: tunnel-secret-volume
          secret:
            secretName: {{ include "cloudflared.name" . }}-tunnel-secret
            defaultMode: 420
            optional: false
        - name: cloudflared-config-volume
          configMap:
            name: {{ include "cloudflared.name" . }}-config
            defaultMode: 420
            optional: false
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 6 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
{{ toYaml .Values.topologySpreadConstraints | indent 8 }}
{{- end }}
{{- end }}
